### ISSUE TITLE
获取不到openId怎么回事？

### ISSUE THREAD

**Issue by tydqcjj** [Voyzz/Fruit-store-mp#3]
云函数都上传部署了，但还是报错。
`VM156:1 thirdScriptError
Cannot read property 'openId' of undefined;at pages/homepage/homepage onLoad function;at api cloud.callFunction complete callback function
TypeError: Cannot read property 'openId' of undefined
    at Function.complete (http://127.0.0.1:22958/appservice/pages/homepage/homepage.js:26:32)
    at Function.<anonymous> (http://127.0.0.1:22958/appservice/__dev__/WAService.js:1:101815)
    at http://127.0.0.1:22958/appservice/__dev__/WAService.js:1:192859
    at i (http://127.0.0.1:22958/appservice/__dev__/WAService.js:1:192568)
    at http://127.0.0.1:22958/appservice/__dev__/WAService.js:1:192837
    at s (http://127.0.0.1:22958/appservice/__dev__/WAService.js:1:131968)
    at Object.t.invokeFailCompleteCallbacks (http://127.0.0.1:22958/appservice/__dev__/WAService.js:1:132171)
    at http://127.0.0.1:22958/appservice/__dev__/WAService.js:1:173140
    at <anonymous>`

应该是云函数没有成功执行。请问这是什么原因？

**Comment by weiping1988** [comment]
同问

**Comment by Qiuqiu82** [comment]
同问
